FROM mysql:8.0

ENV MYSQL_DATABASE=library \
    MYSQL_USER=library \
    MYSQL_PASSWORD=library \
    MYSQL_ROOT_PASSWORD=root

# Charset + collation dla PL/UTF-8 i sensownego sortowania
CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci"]

COPY DBSchema.sql /docker-entrypoint-initdb.d/01_DBSchema.sql
COPY DummyData.sql /docker-entrypoint-initdb.d/02_DummyData.sql
